// test-dir/conda-app/frameworks/vue/CondaComponents.vue
<script setup>
// CONDA Vue 3 Components Library - Composition API
import { ref, computed, watch, onMounted, onUnmounted } from 'vue';
</script>

<script>
// Button Component
export const CondaButton = {
  name: 'CondaButton',
  props: {
    variant: { type: String, default: 'primary' },
    size: { type: String, default: 'medium' },
    disabled: Boolean
  },
  template: `
    <button 
      :class="['conda-button', \`conda-button-\${variant}\`, \`conda-button-\${size}\`]"
      :disabled="disabled"
      @click="$emit('click', $event)"
    >
      <slot />
    </button>
  `
};

// Modal Component
export const CondaModal = {
  name: 'CondaModal',
  props: {
    modelValue: Boolean,
    title: String,
    size: { type: String, default: 'medium' },
    closeOnOverlay: { type: Boolean, default: true },
    showClose: { type: Boolean, default: true }
  },
  emits: ['update:modelValue', 'close'],
  setup(props, { emit }) {
    const close = () => {
      emit('update:modelValue', false);
      emit('close');
    };
    
    const handleOverlay = (e) => {
      if (props.closeOnOverlay && e.target === e.currentTarget) {
        close();
      }
    };
    
    const handleEscape = (e) => {
      if (e.key === 'Escape' && props.modelValue) {
        close();
      }
    };
    
    watch(() => props.modelValue, (isOpen) => {
      document.body.style.overflow = isOpen ? 'hidden' : '';
    });
    
    onMounted(() => {
      document.addEventListener('keydown', handleEscape);
    });
    
    onUnmounted(() => {
      document.removeEventListener('keydown', handleEscape);
      document.body.style.overflow = '';
    });
    
    return { close, handleOverlay };
  },
  template: `
    <Teleport to="body">
      <div v-if="modelValue" :class="['conda-modal-overlay', { active: modelValue }]" @click="handleOverlay">
        <div :class="['conda-modal', \`conda-modal-\${size}\`]" role="dialog" aria-modal="true">
          <div class="conda-modal-header">
            <h2 class="conda-modal-title">{{ title }}</h2>
            <button v-if="showClose" class="conda-modal-close" @click="close" aria-label="Close">&times;</button>
          </div>
          <div class="conda-modal-body">
            <slot />
          </div>
          <div v-if="$slots.footer" class="conda-modal-footer">
            <slot name="footer" />
          </div>
        </div>
      </div>
    </Teleport>
  `
};

// Tabs Component
export const CondaTabs = {
  name: 'CondaTabs',
  props: {
    modelValue: { type: Number, default: 0 }
  },
  emits: ['update:modelValue', 'change'],
  setup(props, { emit, slots }) {
    const activeTab = ref(props.modelValue);
    
    const selectTab = (index) => {
      activeTab.value = index;
      emit('update:modelValue', index);
      emit('change', index);
    };
    
    watch(() => props.modelValue, (val) => {
      activeTab.value = val;
    });
    
    return { activeTab, selectTab };
  },
  template: `
    <div class="conda-tabs">
      <div class="conda-tabs-nav" role="tablist">
        <button
          v-for="(tab, index) in $slots.default()"
          :key="index"
          :class="['conda-tab-button', { active: activeTab === index }]"
          @click="selectTab(index)"
          role="tab"
          :aria-selected="activeTab === index"
        >
          {{ tab.props?.label }}
        </button>
      </div>
      <div
        v-for="(tab, index) in $slots.default()"
        :key="index"
        :class="['conda-tab-content', { active: activeTab === index }]"
        role="tabpanel"
      >
        <component :is="tab" v-if="activeTab === index" />
      </div>
    </div>
  `
};

export const CondaTab = {
  name: 'CondaTab',
  props: { label: String, icon: String },
  template: '<div><slot /></div>'
};

// Input Component  
export const CondaInput = {
  name: 'CondaInput',
  props: {
    modelValue: [String, Number],
    label: String,
    error: String,
    helpText: String,
    required: Boolean
  },
  emits: ['update:modelValue'],
  template: `
    <div class="conda-form-group">
      <label v-if="label" :class="['conda-form-label', { required }]">{{ label }}</label>
      <input
        :value="modelValue"
        @input="$emit('update:modelValue', $event.target.value)"
        :class="['conda-form-input', { error }]"
        v-bind="$attrs"
      />
      <span v-if="helpText" class="conda-form-help">{{ helpText }}</span>
      <span v-if="error" class="conda-form-error">{{ error }}</span>
    </div>
  `
};

export default {
  CondaButton,
  CondaModal,
  CondaTabs,
  CondaTab,
  CondaInput
};
</script>

// test-dir/conda-app/frameworks/web-components/conda-components.js
// ============================================
// CONDA Web Components (Custom Elements)
// Framework-agnostic reusable components
// ============================================

// Button Component
class CondaButtonElement extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }
  
  connectedCallback() {
    const variant = this.getAttribute('variant') || 'primary';
    const size = this.getAttribute('size') || 'medium';
    const disabled = this.hasAttribute('disabled');
    
    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="../../src/styles/conda-design-system.css">
      <button class="conda-button conda-button-${variant} conda-button-${size}" ${disabled ? 'disabled' : ''}>
        <slot></slot>
      </button>
    `;
    
    this.shadowRoot.querySelector('button').addEventListener('click', (e) => {
      this.dispatchEvent(new CustomEvent('conda-click', { detail: e, bubbles: true }));
    });
  }
}

// Modal Component
class CondaModalElement extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open' });
  }
  
  connectedCallback() {
    this.render();
    this.attachEvents();
  }
  
  render() {
    const title = this.getAttribute('title') || 'Modal';
    const size = this.getAttribute('size') || 'medium';
    const isOpen = this.hasAttribute('open');
    
    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="../../src/styles/conda-design-system.css">
      <link rel="stylesheet" href="../../src/styles/components.css">
      <div class="conda-modal-overlay ${isOpen ? 'active' : ''}">
        <div class="conda-modal conda-modal-${size}" role="dialog">
          <div class="conda-modal-header">
            <h2 class="conda-modal-title">${title}</h2>
            <button class="conda-modal-close">&times;</button>
          </div>
          <div class="conda-modal-body">
            <slot></slot>
          </div>
          <div class="conda-modal-footer">
            <slot name="footer"></slot>
          </div>
        </div>
      </div>
    `;
  }
  
  attachEvents() {
    const closeBtn = this.shadowRoot.querySelector('.conda-modal-close');
    const overlay = this.shadowRoot.querySelector('.conda-modal-overlay');
    
    closeBtn?.addEventListener('click', () => this.close());
    overlay?.addEventListener('click', (e) => {
      if (e.target === overlay) this.close();
    });
  }
  
  open() {
    this.setAttribute('open', '');
    this.shadowRoot.querySelector('.conda-modal-overlay').classList.add('active');
    document.body.style.overflow = 'hidden';
  }
  
  close() {
    this.removeAttribute('open');
    this.shadowRoot.querySelector('.conda-modal-overlay').classList.remove('active');
    document.body.style.overflow = '';
    this.dispatchEvent(new CustomEvent('conda-close', { bubbles: true }));
  }
}

// Tabs Component
class CondaTabsElement extends HTMLElement {
  constructor() {
    super();
    this.attachShadow({ mode: 'open'});
    this.activeTab = 0;
  }
  
  connectedCallback() {
    this.render();
    this.attachEvents();
  }
  
  render() {
    const tabs = Array.from(this.querySelectorAll('conda-tab'));
    
    this.shadowRoot.innerHTML = `
      <link rel="stylesheet" href="../../src/styles/conda-design-system.css">
      <link rel="stylesheet" href="../../src/styles/components.css">
      <div class="conda-tabs">
        <div class="conda-tabs-nav" role="tablist">
          ${tabs.map((tab, i) => `
            <button 
              class="conda-tab-button ${i === this.activeTab ? 'active' : ''}"
              data-index="${i}"
              role="tab"
            >
              ${tab.getAttribute('label')}
            </button>
          `).join('')}
        </div>
        <div class="tab-panels">
          <slot></slot>
        </div>
      </div>
    `;
  }
  
  attachEvents() {
    this.shadowRoot.querySelectorAll('.conda-tab-button').forEach((btn, index) => {
      btn.addEventListener('click', () => this.selectTab(index));
    });
  }
  
  selectTab(index) {
    this.activeTab = index;
    this.shadowRoot.querySelectorAll('.conda-tab-button').forEach((btn, i) => {
      btn.classList.toggle('active', i === index);
    });
    
    this.querySelectorAll('conda-tab').forEach((tab, i) => {
      tab.style.display = i === index ? 'block' : 'none';
    });
    
    this.dispatchEvent(new CustomEvent('conda-tab-change', { 
      detail: { index }, 
      bubbles: true 
    }));
  }
}

class CondaTabElement extends HTMLElement {
  constructor() {
    super();
  }
}

// Register all components
customElements.define('conda-button', CondaButtonElement);
customElements.define('conda-modal', CondaModalElement);
customElements.define('conda-tabs', CondaTabsElement);
customElements.define('conda-tab', CondaTabElement);

// Export for module use
export { CondaButtonElement, CondaModalElement, CondaTabsElement, CondaTabElement };
